default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: cms_development

test:
  <<: *default
  database: cms_test

production:
  <<: *default
  database: cms_production
